WITH CTE_SURGERY_BASE AS (
    SELECT DISTINCT
        SCF.SURGICALCASEKEY,
        SCF.SURGICALCASEEPICID,
        SCF.HOSPITALENCOUNTERKEY,
        DEP.PARENTLOCATIONNAME AS DEPARTMENTNAME,
        SCF.PATIENTDURABLEKEY AS PDK,
        SCF.SURGERYDATEKEY,
        DD.DATEVALUE AS SURGERY_DATE,
        SCF.ASARATING_X AS ASARATING_X,
        PROV.NAME AS SURGEON_NAME,
        SCF.PRIMARYPROCEDUREDURABLEKEY,
        SCF.PRIMARYPROCEDUREAPPROACH,
        SCF.PRIMARYANESTHESIATYPE,
        SCF.PROCEDURENOTPERFORMED,
        SCF.ANESTHESIASTARTDATEKEY,
        SCF.ANESTHESIASTARTTIMEOFDAYKEY,
        SCF.ANESTHESIASTOPTIMEOFDAYKEY,
        SCF.PROCEDURESTARTTIMEOFDAYKEY,
        SCF.PROCEDURECOMPLETETIMEOFDAYKEY,
        SCF.HADSURGICALSITEINFECTION,
        SCF.SURGICALSITEINFECTIONRISKSCORE,
        SCF.WASPERIPHERALNERVEBLOCKPERFORMED,
        SCF.HADOTHERCOMPLICATION,
        SCF.RETURNTOSURGERYINDAYS,
        SCF.TOTALCOST,
        SCF.HOSPITALSURGICALCOST,
        SCF.IMPLANTABLESUPPLYUSEDCOST,
        SCF.HASASTHMA,
        SCF.HASCHRONICKIDNEYDISEASE,
        SCF.HASCONGESTIVEHEARTFAILURE,
        SCF.HASCOPD,
        SCF.HASDIABETES,
        SCF.HASHIV,
        SCF.HASHYPERTENSION,
        SCF.HIGHESTPACUPAINSCORE
    FROM CABOODLE.SURGICALCASEFACT SCF
    INNER JOIN CABOODLE.SURGICALPROCEDUREEVENTFACT SPEF
        ON SCF.SURGICALCASEKEY = SPEF.SURGICALCASEKEY
       AND SPEF.ISPRIMARY = 1
       AND SPEF.PERFORMED = 1
    INNER JOIN CLARITY.OR_CASE_ADDL_CODES CODES
        ON SCF.SURGICALCASEEPICID = CODES.CASE_ID
    INNER JOIN CLARITY.CLARITY_EAP EAP
        ON CODES.OR_CASE_ADDL_CODE_ID = EAP.PROC_ID
    INNER JOIN CABOODLE.PROVIDERDIM PROV
        ON SCF.PRIMARYSURGEONKEY = PROV.PROVIDERKEY
    INNER JOIN CABOODLE.PATIENTDIM PAT_S
        ON SCF.PATIENTDURABLEKEY = PAT_S.DURABLEKEY
       AND PAT_S.ISCURRENT = 1
       AND PAT_S.ISVALID = 1
    INNER JOIN CABOODLE.DATEDIM DD
        ON SCF.SURGERYDATEKEY = DD.DATEKEY
     INNER JOIN CABOODLE.DEPARTMENTDIM DEP
        ON SCF.LOCATIONKEY = DEP.DEPARTMENTKEY
    WHERE DD.DATEVALUE >= DATEADD(YEAR, -5, CURRENT_DATE)
      AND EAP.PROC_CODE IN (
            '29806','23455','29828','23430','23440','23020','29825',
            '23450','29822','23470','23616','23120','29824','17999','29827'
      )
      AND UPPER(PROV.NAME) LIKE '%OSHIKOYA%'

),

CTE_CASE_PROCEDURE AS (

    WITH CPTS AS (

        SELECT
            S.SURGICALCASEKEY,
            EAP.PROC_NAME,
            EAP.PROC_CODE,
            ROW_NUMBER() OVER (
                PARTITION BY S.SURGICALCASEKEY
                ORDER BY EAP.PROC_CODE
            ) AS RN
        FROM CTE_SURGERY_BASE S
        INNER JOIN CLARITY.OR_CASE_ADDL_CODES CODES
            ON S.SURGICALCASEEPICID = CODES.CASE_ID
        INNER JOIN CLARITY.CLARITY_EAP EAP
            ON CODES.OR_CASE_ADDL_CODE_ID = EAP.PROC_ID

    )

    SELECT
        SURGICALCASEKEY,

        LISTAGG(DISTINCT PROC_NAME, ' || ')
            WITHIN GROUP (ORDER BY PROC_NAME) AS PROCEDURE_NAME,

        LISTAGG(DISTINCT PROC_CODE, ' || ')
            WITHIN GROUP (ORDER BY PROC_CODE) AS CPTCODE,

        MAX(CASE
                WHEN RN = 1 THEN PROC_CODE
            END) AS PRIMARYCPT

    FROM CPTS
    GROUP BY SURGICALCASEKEY
),
CTE_BILLING_ACCOUNT AS (
    SELECT
        X.SURGICALCASEKEY,
        X.FINANCIALCLASS,
        X.ADMISSIONDATEKEY,
        X.ADMISSIONTIMEOFDAYKEY,
        X.DISCHARGEDATEKEY,
        X.DISCHARGETIMEOFDAYKEY,
        X.INPATIENTBILLINGLENGTHOFSTAYINDAYS
    FROM (
        SELECT
            S.SURGICALCASEKEY,
            BA.FINANCIALCLASS,
            BA.ADMISSIONDATEKEY,
            BA.ADMISSIONTIMEOFDAYKEY,
            BA.DISCHARGEDATEKEY,
            BA.DISCHARGETIMEOFDAYKEY,
            BA.INPATIENTBILLINGLENGTHOFSTAYINDAYS,
            ROW_NUMBER() OVER (
                PARTITION BY S.SURGICALCASEKEY
                ORDER BY BA.ADMISSIONDATEKEY DESC, BA.DISCHARGEDATEKEY DESC
            ) AS RN
        FROM CTE_SURGERY_BASE S
        LEFT JOIN CABOODLE.ENCOUNTERFACT E
            ON S.HOSPITALENCOUNTERKEY = E.ENCOUNTERKEY
        LEFT JOIN CABOODLE.BILLINGACCOUNTFACT BA
            ON E.ENCOUNTERKEY = BA.PRIMARYENCOUNTERKEY
    ) X
    WHERE X.RN = 1
),

CTE_INDEX_STAY AS (
    SELECT
        S.SURGICALCASEKEY,
        S.PDK,
        B.ADMISSIONDATEKEY,
        B.ADMISSIONTIMEOFDAYKEY,
        B.DISCHARGEDATEKEY,
        B.DISCHARGETIMEOFDAYKEY,
        ADT.DATEVALUE AS ADMISSION_DATE,
        DDT.DATEVALUE AS DISCHARGE_DATE,
        B.FINANCIALCLASS,
        B.INPATIENTBILLINGLENGTHOFSTAYINDAYS
    FROM CTE_SURGERY_BASE S
    LEFT JOIN CTE_BILLING_ACCOUNT B
        ON S.SURGICALCASEKEY = B.SURGICALCASEKEY
    LEFT JOIN CABOODLE.DATEDIM ADT
        ON B.ADMISSIONDATEKEY = ADT.DATEKEY
    LEFT JOIN CABOODLE.DATEDIM DDT
        ON B.DISCHARGEDATEKEY = DDT.DATEKEY
),

CTE_DIAGNOSIS AS (
    SELECT
        S.SURGICALCASEKEY,
        LISTAGG(DISTINCT DX.NAME, ' || ')
            WITHIN GROUP (ORDER BY DX.NAME) AS DIAGNOSIS
    FROM CTE_SURGERY_BASE S
    INNER JOIN CABOODLE.ENCOUNTERFACT E
        ON S.HOSPITALENCOUNTERKEY = E.ENCOUNTERKEY
    INNER JOIN CABOODLE.DIAGNOSISDIM DX
        ON E.PRIMARYDIAGNOSISKEY = DX.DIAGNOSISKEY
    WHERE E.PRIMARYDIAGNOSISKEY IS NOT NULL
    GROUP BY S.SURGICALCASEKEY
),

CTE_SOCIAL_DETERMINANTS AS (
    SELECT
        S.SURGICALCASEKEY,
        LISTAGG(DISTINCT SDF.SOCIALDETERMINANTDOMAIN, ' || ')
            WITHIN GROUP (ORDER BY SDF.SOCIALDETERMINANTDOMAIN) AS SOCIALDETERMINANTDOMAIN,
        LISTAGG(DISTINCT SDF.LEVELOFCONCERN, ' || ')
            WITHIN GROUP (ORDER BY SDF.LEVELOFCONCERN) AS LEVELOFCONCERN,
        LISTAGG(DISTINCT SDF.ENTRYINTERPRETATION, ' || ')
            WITHIN GROUP (ORDER BY SDF.ENTRYINTERPRETATION) AS ENTRYINTERPRETATION
    FROM CTE_SURGERY_BASE S
    INNER JOIN CABOODLE.ENCOUNTERFACT E
        ON S.HOSPITALENCOUNTERKEY = E.ENCOUNTERKEY
    INNER JOIN CABOODLE.SOCIALDETERMINANTFACT SDF
        ON E.ENCOUNTERKEY = SDF.ENCOUNTERKEY
    GROUP BY S.SURGICALCASEKEY
),

CTE_PATIENT_DIAG_FLAGS AS (
    SELECT
        S.PDK,

        MAX(CASE
                WHEN DXT.VALUE = 'G4733'
                  OR DXT.DISPLAYSTRING ILIKE '%sleep apnea%'
                THEN 1 ELSE 0
            END) AS OSA_FLAG,

        MAX(CASE
                WHEN DXT.VALUE LIKE 'I21%'
                  OR DXT.VALUE LIKE 'I22%'
                  OR DXT.VALUE LIKE 'I25%'
                THEN 1 ELSE 0
            END) AS CAD_MI_FLAG,

        MAX(CASE
                WHEN DXT.VALUE LIKE 'I47%'
                  OR DXT.VALUE LIKE 'I48%'
                  OR DXT.VALUE LIKE 'I49%'
                THEN 1 ELSE 0
            END) AS ARRHYTHMIA_FLAG,

        MAX(CASE
                WHEN DXT.VALUE LIKE 'F41%'
                THEN 1 ELSE 0
            END) AS ANXIETY_FLAG,

        MAX(CASE
                WHEN DXT.VALUE LIKE 'F03%'
                  OR DXT.VALUE LIKE 'G30%'
                THEN 1 ELSE 0
            END) AS DEMENTIA_FLAG,

        MAX(CASE
                WHEN DXT.VALUE LIKE 'G81%'
                  OR DXT.VALUE LIKE 'G82%'
                  OR DXT.VALUE = 'R532'
                  OR DXT.VALUE LIKE 'Z74%'
                THEN 1 ELSE 0
            END) AS FUNCTIONAL_DISABILITY_FLAG

    FROM CTE_SURGERY_BASE S
    LEFT JOIN CABOODLE.DIAGNOSISEVENTFACT DEF
        ON S.PDK = DEF.PATIENTDURABLEKEY
       AND DEF.COUNT = 1
       AND DEF.TYPE IN ('Encounter Diagnosis', 'Encounter Diagnosis from External Source')
    LEFT JOIN CABOODLE.DIAGNOSISTERMINOLOGYDIM DXT
        ON DEF.DIAGNOSISKEY = DXT.DIAGNOSISKEY
       AND DXT.TYPE = 'ICD-10-CM'
    GROUP BY S.PDK
),
CTE_CLOSEST_VITALS AS (
    SELECT
        x.SURGICALCASEKEY,
        x.PDK,
        x.BMIVALUE,
        x.CURRENTHEIGHT,
        x.CURRENTWEIGHT
    FROM (
        SELECT
            S.SURGICALCASEKEY,
            S.PDK,
            V.BMIVALUE,
            V.CURRENTHEIGHT,
            V.CURRENTWEIGHT,
            V.BMIRECORDEDDATE,
            ROW_NUMBER() OVER (
                PARTITION BY S.SURGICALCASEKEY
                ORDER BY V.BMIRECORDEDDATE DESC
            ) AS RN
        FROM CTE_SURGERY_BASE S
        INNER JOIN stage.rdsc.rdsc_epic_pt_vitallabresults V
             ON V.PATIENTDURABLEKEY = S.PDK
          AND V.BMIRECORDEDDATE <= CAST(S.SURGERY_DATE AS TIMESTAMP_NTZ)
   
    ) x
    WHERE x.RN = 1
),


CTE_COMORBIDITIES AS (
    SELECT
        S.SURGICALCASEKEY,
        S.PDK,
        MAX(S.ASARATING_X) AS ASARATING_X,
        MAX(HRA.CHARLSONCOMORBIDITYINDEX) AS CHARLSON_COMORBIDITY_INDEX,
        LISTAGG(DISTINCT PAT.SMOKINGSTATUS, ' || ')
            WITHIN GROUP (ORDER BY PAT.SMOKINGSTATUS) AS SMOKING_STATUS,
        MAX(CV.BMIVALUE) AS BODYMASSINDEX,
MAX(CV.CURRENTHEIGHT) AS HEIGHT,
MAX(CV.CURRENTWEIGHT) AS WEIGHT,
        MAX(HRA.FUNCTIONALSTATUS) AS FUNCTIONALSTATUS,
        MAX(HRA.LIVINGSITUATION) AS LIVINGSITUATION,
        MAX(HRA.MENTALHEALTHSTATUS) AS MENTALHEALTHSTATUS,
        MAX(CASE WHEN HRA.NUMBEROFDAYSSINCELASTADMISSION <= 90 THEN 1 ELSE 0 END) AS RECENT_HOSPITALIZATION_90D_FLAG,

        MAX(COALESCE(PDF.OSA_FLAG, 0)) AS OSA_FLAG,
        MAX(COALESCE(PDF.CAD_MI_FLAG, 0)) AS CAD_MI_FLAG,
        MAX(COALESCE(PDF.ARRHYTHMIA_FLAG, 0)) AS ARRHYTHMIA_FLAG,
        MAX(COALESCE(PDF.ANXIETY_FLAG, 0)) AS ANXIETY_FLAG,
        MAX(COALESCE(PDF.DEMENTIA_FLAG, 0)) AS DEMENTIA_FLAG,
        MAX(COALESCE(PDF.FUNCTIONAL_DISABILITY_FLAG, 0)) AS FUNCTIONAL_DISABILITY_FLAG

    FROM CTE_SURGERY_BASE S
    LEFT JOIN CABOODLE.HOSPITALREADMISSIONANALYTICSDATAMART HRA
        ON S.PDK = HRA.PATIENTDURABLEKEY
    LEFT JOIN CABOODLE.PATIENTDIM PAT
        ON S.PDK = PAT.DURABLEKEY
       AND PAT.ISCURRENT = 1
   LEFT JOIN CTE_CLOSEST_VITALS CV
    ON S.SURGICALCASEKEY = CV.SURGICALCASEKEY
    LEFT JOIN CTE_PATIENT_DIAG_FLAGS PDF
        ON S.PDK = PDF.PDK
    GROUP BY
        S.SURGICALCASEKEY,
        S.PDK
),
CTE_ELIX_MISSING AS (
SELECT
S.SURGICALCASEKEY,
S.PDK,


    MAX(CASE WHEN DXT.VALUE LIKE 'I50%' OR DXT.VALUE = 'I09.81' OR DXT.VALUE LIKE '428.%' OR DXT.VALUE LIKE '398.91'
             THEN 1 ELSE 0 END) AS ELIX_CHF,

    MAX(CASE WHEN DXT.VALUE = 'B20' OR DXT.VALUE LIKE '042%' OR DXT.VALUE LIKE '043%' OR DXT.VALUE LIKE '044%'
             THEN 1 ELSE 0 END) AS ELIX_AIDS,

    MAX(CASE WHEN DXT.VALUE LIKE 'F10%' OR DXT.VALUE LIKE '291.%' OR DXT.VALUE LIKE '303.%' OR DXT.VALUE LIKE '305.0%'
             THEN 1 ELSE 0 END) AS ELIX_ALCOHOL,

    MAX(CASE WHEN DXT.VALUE LIKE 'D50%' OR DXT.VALUE LIKE 'D51%' OR DXT.VALUE LIKE 'D52%' OR DXT.VALUE LIKE 'D53%'
              OR DXT.VALUE LIKE 'D63%' OR DXT.VALUE LIKE 'D64%'
              OR DXT.VALUE LIKE '280%' OR DXT.VALUE LIKE '281%' OR DXT.VALUE LIKE '285.2%' OR DXT.VALUE LIKE '285.9%'
             THEN 1 ELSE 0 END) AS ELIX_ANEMDEF,

    MAX(CASE WHEN DXT.VALUE LIKE 'M05%' OR DXT.VALUE LIKE 'M06%' OR DXT.VALUE LIKE 'M08%'
              OR DXT.VALUE LIKE 'M12%' OR DXT.VALUE LIKE 'M32%' OR DXT.VALUE LIKE 'M33%'
              OR DXT.VALUE LIKE 'M34%' OR DXT.VALUE LIKE 'M35%' OR DXT.VALUE LIKE 'M45%'
              OR DXT.VALUE LIKE 'M46%' OR DXT.VALUE LIKE 'L40%'
             THEN 1 ELSE 0 END) AS ELIX_ARTH,

    MAX(CASE WHEN DXT.VALUE IN ('D50.0')
              OR DXT.VALUE LIKE 'O90.81'
              OR DXT.VALUE LIKE 'O99.01%'
              OR DXT.VALUE LIKE 'O99.02'
              OR DXT.VALUE LIKE 'O99.03'
              OR DXT.VALUE LIKE '280.0'
              OR DXT.VALUE LIKE '648.2%'
             THEN 1 ELSE 0 END) AS ELIX_BLDLOSS,

    MAX(CASE WHEN DXT.VALUE LIKE 'J40%' OR DXT.VALUE LIKE 'J41%' OR DXT.VALUE LIKE 'J42%'
              OR DXT.VALUE LIKE 'J43%' OR DXT.VALUE LIKE 'J44%' OR DXT.VALUE LIKE 'J45%'
              OR DXT.VALUE LIKE 'J47%' OR DXT.VALUE LIKE 'J60%' OR DXT.VALUE LIKE 'J61%'
              OR DXT.VALUE LIKE 'J62%' OR DXT.VALUE LIKE 'J63%' OR DXT.VALUE LIKE 'J64%'
              OR DXT.VALUE LIKE 'J66%' OR DXT.VALUE LIKE 'J67%' OR DXT.VALUE LIKE 'J68.4'
              OR DXT.VALUE LIKE '490%' OR DXT.VALUE LIKE '491%' OR DXT.VALUE LIKE '492%'
              OR DXT.VALUE LIKE '493.%' OR DXT.VALUE LIKE '494%' OR DXT.VALUE LIKE '495.%'
              OR DXT.VALUE LIKE '496%' OR DXT.VALUE LIKE '497%' OR DXT.VALUE LIKE '498%'
              OR DXT.VALUE LIKE '499%' OR DXT.VALUE LIKE '500%' OR DXT.VALUE LIKE '501%'
              OR DXT.VALUE LIKE '502%' OR DXT.VALUE LIKE '503%' OR DXT.VALUE LIKE '504%'
              OR DXT.VALUE LIKE '505%' OR DXT.VALUE LIKE '506.4'
             THEN 1 ELSE 0 END) AS ELIX_CHRNLUNG,

    MAX(CASE WHEN DXT.VALUE LIKE 'D65%' OR DXT.VALUE LIKE 'D66%' OR DXT.VALUE LIKE 'D67%'
              OR DXT.VALUE LIKE 'D68%' OR DXT.VALUE LIKE 'D69%'
              OR DXT.VALUE LIKE '286.%' OR DXT.VALUE LIKE '287.%' OR DXT.VALUE LIKE '289.84'
             THEN 1 ELSE 0 END) AS ELIX_COAG,

    MAX(CASE WHEN DXT.VALUE LIKE 'F32%' OR DXT.VALUE LIKE 'F33%' OR DXT.VALUE = 'F34.1'
              OR DXT.VALUE = 'F43.21' OR DXT.VALUE LIKE '300.4' OR DXT.VALUE LIKE '301.12'
              OR DXT.VALUE LIKE '309.0' OR DXT.VALUE LIKE '309.1' OR DXT.VALUE LIKE '311'
             THEN 1 ELSE 0 END) AS ELIX_DEPRESS,

    MAX(CASE WHEN DXT.VALUE LIKE 'E08%' OR DXT.VALUE LIKE 'E09%' OR DXT.VALUE LIKE 'E10%'
              OR DXT.VALUE LIKE 'E11%' OR DXT.VALUE LIKE 'E13%'
              OR DXT.VALUE LIKE '249.%' OR DXT.VALUE LIKE '250.%'
             THEN 1 ELSE 0 END) AS ELIX_DM,

    MAX(CASE WHEN DXT.VALUE LIKE 'E08.21%' OR DXT.VALUE LIKE 'E08.22%' OR DXT.VALUE LIKE 'E08.29%'
              OR DXT.VALUE LIKE 'E08.31%' OR DXT.VALUE LIKE 'E08.32%' OR DXT.VALUE LIKE 'E08.33%'
              OR DXT.VALUE LIKE 'E08.34%' OR DXT.VALUE LIKE 'E08.35%' OR DXT.VALUE LIKE 'E08.36%'
              OR DXT.VALUE LIKE 'E08.37%' OR DXT.VALUE LIKE 'E08.39%' OR DXT.VALUE LIKE 'E08.4%'
              OR DXT.VALUE LIKE 'E08.5%' OR DXT.VALUE LIKE 'E08.6%' OR DXT.VALUE LIKE 'E08.8%'
              OR DXT.VALUE LIKE 'E09.21%' OR DXT.VALUE LIKE 'E09.22%' OR DXT.VALUE LIKE 'E09.29%'
              OR DXT.VALUE LIKE 'E09.31%' OR DXT.VALUE LIKE 'E09.32%' OR DXT.VALUE LIKE 'E09.33%'
              OR DXT.VALUE LIKE 'E09.34%' OR DXT.VALUE LIKE 'E09.35%' OR DXT.VALUE LIKE 'E09.36%'
              OR DXT.VALUE LIKE 'E09.37%' OR DXT.VALUE LIKE 'E09.39%' OR DXT.VALUE LIKE 'E09.4%'
              OR DXT.VALUE LIKE 'E09.5%' OR DXT.VALUE LIKE 'E09.6%' OR DXT.VALUE LIKE 'E09.8%'
              OR DXT.VALUE LIKE 'E10.21%' OR DXT.VALUE LIKE 'E10.22%' OR DXT.VALUE LIKE 'E10.29%'
              OR DXT.VALUE LIKE 'E10.31%' OR DXT.VALUE LIKE 'E10.32%' OR DXT.VALUE LIKE 'E10.33%'
              OR DXT.VALUE LIKE 'E10.34%' OR DXT.VALUE LIKE 'E10.35%' OR DXT.VALUE LIKE 'E10.36%'
              OR DXT.VALUE LIKE 'E10.37%' OR DXT.VALUE LIKE 'E10.39%' OR DXT.VALUE LIKE 'E10.4%'
              OR DXT.VALUE LIKE 'E10.5%' OR DXT.VALUE LIKE 'E10.6%' OR DXT.VALUE LIKE 'E10.8%'
              OR DXT.VALUE LIKE 'E11.21%' OR DXT.VALUE LIKE 'E11.22%' OR DXT.VALUE LIKE 'E11.29%'
              OR DXT.VALUE LIKE 'E11.31%' OR DXT.VALUE LIKE 'E11.32%' OR DXT.VALUE LIKE 'E11.33%'
              OR DXT.VALUE LIKE 'E11.34%' OR DXT.VALUE LIKE 'E11.35%' OR DXT.VALUE LIKE 'E11.36%'
              OR DXT.VALUE LIKE 'E11.37%' OR DXT.VALUE LIKE 'E11.39%' OR DXT.VALUE LIKE 'E11.4%'
              OR DXT.VALUE LIKE 'E11.5%' OR DXT.VALUE LIKE 'E11.6%' OR DXT.VALUE LIKE 'E11.8%'
              OR DXT.VALUE LIKE 'E13.21%' OR DXT.VALUE LIKE 'E13.22%' OR DXT.VALUE LIKE 'E13.29%'
              OR DXT.VALUE LIKE 'E13.31%' OR DXT.VALUE LIKE 'E13.32%' OR DXT.VALUE LIKE 'E13.33%'
              OR DXT.VALUE LIKE 'E13.34%' OR DXT.VALUE LIKE 'E13.35%' OR DXT.VALUE LIKE 'E13.36%'
              OR DXT.VALUE LIKE 'E13.37%' OR DXT.VALUE LIKE 'E13.39%' OR DXT.VALUE LIKE 'E13.4%'
              OR DXT.VALUE LIKE 'E13.5%' OR DXT.VALUE LIKE 'E13.6%' OR DXT.VALUE LIKE 'E13.8%'
             THEN 1 ELSE 0 END) AS ELIX_DMCX,

    MAX(CASE WHEN DXT.VALUE LIKE 'F11%' OR DXT.VALUE LIKE 'F12%' OR DXT.VALUE LIKE 'F13%'
              OR DXT.VALUE LIKE 'F14%' OR DXT.VALUE LIKE 'F15%' OR DXT.VALUE LIKE 'F16%'
              OR DXT.VALUE LIKE 'F18%' OR DXT.VALUE LIKE 'F19%'
              OR DXT.VALUE LIKE '292.%' OR DXT.VALUE LIKE '304.%' OR DXT.VALUE LIKE '305.2%'
              OR DXT.VALUE LIKE '305.3%' OR DXT.VALUE LIKE '305.4%' OR DXT.VALUE LIKE '305.5%'
              OR DXT.VALUE LIKE '305.6%' OR DXT.VALUE LIKE '305.7%' OR DXT.VALUE LIKE '305.8%'
              OR DXT.VALUE LIKE '305.9%'
             THEN 1 ELSE 0 END) AS ELIX_DRUG,

    MAX(CASE WHEN DXT.VALUE IN ('I13.0') OR DXT.VALUE LIKE '404.01' OR DXT.VALUE LIKE '404.11'
              OR DXT.VALUE LIKE '404.91'
             THEN 1 ELSE 0 END) AS ELIX_HHRWCHF,

    MAX(CASE WHEN DXT.VALUE IN ('I13.2') OR DXT.VALUE LIKE '404.03' OR DXT.VALUE LIKE '404.13'
              OR DXT.VALUE LIKE '404.93'
             THEN 1 ELSE 0 END) AS ELIX_HHRWHRF,

    MAX(CASE WHEN DXT.VALUE IN ('I13.10') OR DXT.VALUE LIKE '404.00' OR DXT.VALUE LIKE '404.10'
              OR DXT.VALUE LIKE '404.90'
             THEN 1 ELSE 0 END) AS ELIX_HHRWOHRF,

    MAX(CASE WHEN DXT.VALUE IN ('I13.11') OR DXT.VALUE LIKE '404.02' OR DXT.VALUE LIKE '404.12'
              OR DXT.VALUE LIKE '404.92'
             THEN 1 ELSE 0 END) AS ELIX_HHRWRF,

    MAX(CASE WHEN DXT.VALUE IN ('I12.9','I15.0','I15.1') OR DXT.VALUE LIKE '403.00'
              OR DXT.VALUE LIKE '403.10' OR DXT.VALUE LIKE '403.90'
              OR DXT.VALUE LIKE '405.01' OR DXT.VALUE LIKE '405.11' OR DXT.VALUE LIKE '405.91'
              OR DXT.VALUE LIKE '642.1%'
             THEN 1 ELSE 0 END) AS ELIX_HRENWORF,

    MAX(CASE WHEN DXT.VALUE IN ('I12.0') OR DXT.VALUE LIKE '403.01'
              OR DXT.VALUE LIKE '403.11' OR DXT.VALUE LIKE '403.91'
             THEN 1 ELSE 0 END) AS ELIX_HRENWRF,

    MAX(CASE WHEN DXT.VALUE IN ('I10') OR DXT.VALUE LIKE '401.1%' OR DXT.VALUE LIKE '401.9%'
              OR DXT.VALUE LIKE '642.0%'
             THEN 1 ELSE 0 END) AS ELIX_HTN,

    MAX(CASE WHEN DXT.VALUE IN ('I16.0','I16.1','I16.9','I67.4') OR DXT.VALUE LIKE '401.0'
              OR DXT.VALUE LIKE '437.2'
             THEN 1 ELSE 0 END) AS ELIX_HTNCX,

    MAX(CASE WHEN DXT.VALUE LIKE 'O10.111%' OR DXT.VALUE LIKE 'O10.112%' OR DXT.VALUE LIKE 'O10.113%'
              OR DXT.VALUE LIKE 'O10.119%' OR DXT.VALUE LIKE 'O10.12%' OR DXT.VALUE LIKE 'O10.13%'
              OR DXT.VALUE LIKE 'O10.211%' OR DXT.VALUE LIKE 'O10.212%' OR DXT.VALUE LIKE 'O10.213%'
              OR DXT.VALUE LIKE 'O10.219%' OR DXT.VALUE LIKE 'O10.22%' OR DXT.VALUE LIKE 'O10.23%'
              OR DXT.VALUE LIKE 'O10.311%' OR DXT.VALUE LIKE 'O10.312%' OR DXT.VALUE LIKE 'O10.313%'
              OR DXT.VALUE LIKE 'O10.319%' OR DXT.VALUE LIKE 'O10.32%' OR DXT.VALUE LIKE 'O10.33%'
              OR DXT.VALUE LIKE 'O10.411%' OR DXT.VALUE LIKE 'O10.412%' OR DXT.VALUE LIKE 'O10.413%'
              OR DXT.VALUE LIKE 'O10.419%' OR DXT.VALUE LIKE 'O10.42%' OR DXT.VALUE LIKE 'O10.43%'
              OR DXT.VALUE LIKE 'O11.1%' OR DXT.VALUE LIKE 'O11.2%' OR DXT.VALUE LIKE 'O11.3%'
              OR DXT.VALUE LIKE 'O11.4%' OR DXT.VALUE LIKE 'O11.5%' OR DXT.VALUE LIKE 'O11.9%'
             THEN 1 ELSE 0 END) AS ELIX_HTNPREG,

    MAX(CASE WHEN DXT.VALUE IN ('I11.0') OR DXT.VALUE LIKE '402.01' OR DXT.VALUE LIKE '402.11'
              OR DXT.VALUE LIKE '402.91'
             THEN 1 ELSE 0 END) AS ELIX_HTNWCHF,

    MAX(CASE WHEN DXT.VALUE IN ('I11.9','I15.2','I15.8','I15.9') OR DXT.VALUE LIKE '402.00'
              OR DXT.VALUE LIKE '402.10' OR DXT.VALUE LIKE '402.90'
              OR DXT.VALUE LIKE '405.09' OR DXT.VALUE LIKE '405.19' OR DXT.VALUE LIKE '405.99'
             THEN 1 ELSE 0 END) AS ELIX_HTNWOCHF,

    MAX(CASE WHEN DXT.VALUE IN ('E00.0','E00.1','E00.2','E00.9','E01.8','E02','E03.0','E03.1','E03.2',
                                'E03.3','E03.8','E03.9','E89.0')
              OR DXT.VALUE LIKE '243%' OR DXT.VALUE LIKE '244%' OR DXT.VALUE LIKE '244.0%'
              OR DXT.VALUE LIKE '244.1%' OR DXT.VALUE LIKE '244.2%' OR DXT.VALUE LIKE '244.8'
              OR DXT.VALUE LIKE '244.9'
             THEN 1 ELSE 0 END) AS ELIX_HYPOTHY,

    MAX(CASE WHEN DXT.VALUE LIKE 'B18.0%' OR DXT.VALUE LIKE 'B18.1%' OR DXT.VALUE LIKE 'B18.2%'
              OR DXT.VALUE LIKE 'I85.0%' OR DXT.VALUE LIKE 'I85.1%'
              OR DXT.VALUE LIKE 'K70.%' OR DXT.VALUE LIKE 'K72.%' OR DXT.VALUE LIKE 'K73.%'
              OR DXT.VALUE LIKE 'K74.%' OR DXT.VALUE LIKE 'K75.4' OR DXT.VALUE LIKE 'K75.81'
              OR DXT.VALUE LIKE 'K76.%' OR DXT.VALUE = 'Z94.4' OR DXT.VALUE LIKE '070.22'
              OR DXT.VALUE LIKE '070.23' OR DXT.VALUE LIKE '070.32' OR DXT.VALUE LIKE '070.33'
              OR DXT.VALUE LIKE '070.44' OR DXT.VALUE LIKE '070.54' OR DXT.VALUE LIKE '456.%'
              OR DXT.VALUE LIKE '571.%' OR DXT.VALUE LIKE '572.3' OR DXT.VALUE LIKE '572.8'
             THEN 1 ELSE 0 END) AS ELIX_LIVER,

    MAX(CASE WHEN DXT.VALUE LIKE 'C81%' OR DXT.VALUE LIKE 'C82%' OR DXT.VALUE LIKE 'C83%'
              OR DXT.VALUE LIKE 'C84%' OR DXT.VALUE LIKE 'C85%' OR DXT.VALUE LIKE 'C86%'
              OR DXT.VALUE LIKE 'C88%' OR DXT.VALUE LIKE 'C90%' OR DXT.VALUE LIKE 'C96%'
             THEN 1 ELSE 0 END) AS ELIX_LYMPH,

    MAX(CASE WHEN DXT.VALUE IN ('E86.0','E86.1','E86.9','E87.0','E87.1','E87.2','E87.3','E87.4',
                                'E87.5','E87.6','E87.70','E87.71','E87.79','E87.8')
              OR DXT.VALUE LIKE '276.%'
             THEN 1 ELSE 0 END) AS ELIX_LYTES,

    MAX(CASE WHEN DXT.VALUE LIKE 'C77.%' OR DXT.VALUE LIKE 'C78.%' OR DXT.VALUE LIKE 'C79.%'
              OR DXT.VALUE LIKE 'C80.%' OR DXT.VALUE LIKE 'C7B.%'
              OR DXT.VALUE LIKE '196.%' OR DXT.VALUE LIKE '197%' OR DXT.VALUE LIKE '198%'
              OR DXT.VALUE LIKE '199%' OR DXT.VALUE LIKE '209.7%' OR DXT.VALUE LIKE '789.51'
             THEN 1 ELSE 0 END) AS ELIX_METS,

    MAX(CASE WHEN DXT.VALUE LIKE 'E75.%' OR DXT.VALUE LIKE 'F84.2' OR DXT.VALUE LIKE 'G10'
              OR DXT.VALUE LIKE 'G11.%' OR DXT.VALUE LIKE 'G12.%' OR DXT.VALUE LIKE 'G13.%'
              OR DXT.VALUE LIKE 'G20' OR DXT.VALUE LIKE 'G21.4' OR DXT.VALUE LIKE 'G24.%'
              OR DXT.VALUE LIKE 'G25.%' OR DXT.VALUE LIKE 'G30.%' OR DXT.VALUE LIKE 'G31.%'
              OR DXT.VALUE LIKE 'G32.81' OR DXT.VALUE LIKE 'G35' OR DXT.VALUE LIKE 'G36.%'
              OR DXT.VALUE LIKE 'G37.%' OR DXT.VALUE LIKE 'G40.%' OR DXT.VALUE LIKE 'G47.411'
              OR DXT.VALUE LIKE 'G47.419' OR DXT.VALUE LIKE 'G47.421' OR DXT.VALUE LIKE 'G47.429'
              OR DXT.VALUE LIKE 'G80.3' OR DXT.VALUE LIKE 'G89.0' OR DXT.VALUE LIKE 'G91.%'
              OR DXT.VALUE LIKE 'G93.%' OR DXT.VALUE = 'G94' OR DXT.VALUE LIKE 'O99.350%'
              OR DXT.VALUE LIKE 'O99.351%' OR DXT.VALUE LIKE 'O99.352%' OR DXT.VALUE LIKE 'O99.353%'
              OR DXT.VALUE LIKE 'O99.354%' OR DXT.VALUE LIKE 'O99.355%'
             THEN 1 ELSE 0 END) AS ELIX_NEURO,

    MAX(CASE WHEN DXT.VALUE LIKE 'E66.%' OR DXT.VALUE LIKE 'O99.21%' OR DXT.VALUE LIKE 'R93.9'
              OR DXT.VALUE LIKE 'Z68.3%' OR DXT.VALUE LIKE 'Z68.4%' OR DXT.VALUE LIKE 'Z68.54'
             THEN 1 ELSE 0 END) AS ELIX_OBESE,

    MAX(CASE WHEN DXT.VALUE LIKE 'O16.%' OR DXT.VALUE LIKE '642.7%' OR DXT.VALUE LIKE '642.9%'
             THEN 1 ELSE 0 END) AS ELIX_OHTNPREG,

    MAX(CASE WHEN DXT.VALUE LIKE 'G04.1' OR DXT.VALUE LIKE 'G80.%' OR DXT.VALUE LIKE 'G81.%'
              OR DXT.VALUE LIKE 'G82.%' OR DXT.VALUE LIKE 'G83.%' OR DXT.VALUE LIKE 'I69.%'
              OR DXT.VALUE = 'R53.2'
             THEN 1 ELSE 0 END) AS ELIX_PARA,

    MAX(CASE WHEN DXT.VALUE LIKE 'I70.%' OR DXT.VALUE LIKE 'I71.%' OR DXT.VALUE LIKE 'I72.%'
              OR DXT.VALUE LIKE 'I73.%' OR DXT.VALUE LIKE 'I74.%' OR DXT.VALUE LIKE 'I76'
              OR DXT.VALUE LIKE 'I77.%' OR DXT.VALUE LIKE 'I79.%' OR DXT.VALUE LIKE 'K55.%'
              OR DXT.VALUE LIKE 'Z95.820' OR DXT.VALUE LIKE 'Z95.828'
             THEN 1 ELSE 0 END) AS ELIX_PERIVASC,

    MAX(CASE WHEN DXT.VALUE LIKE 'F20%' OR DXT.VALUE LIKE 'F22%' OR DXT.VALUE LIKE 'F23%'
              OR DXT.VALUE LIKE 'F24%' OR DXT.VALUE LIKE 'F25%' OR DXT.VALUE LIKE 'F28%'
              OR DXT.VALUE LIKE 'F29%' OR DXT.VALUE LIKE 'F30%' OR DXT.VALUE LIKE 'F31%'
              OR DXT.VALUE LIKE 'F32.4' OR DXT.VALUE LIKE 'F32.5' OR DXT.VALUE LIKE 'F33.40%'
              OR DXT.VALUE LIKE 'F33.41%' OR DXT.VALUE LIKE 'F33.42%' OR DXT.VALUE LIKE 'F34.8%'
              OR DXT.VALUE LIKE 'F39' OR DXT.VALUE LIKE 'F44.89' OR DXT.VALUE LIKE 'F84.3'
             THEN 1 ELSE 0 END) AS ELIX_PSYCH,

    MAX(CASE WHEN DXT.VALUE LIKE 'I26.%' OR DXT.VALUE LIKE 'I27.%' OR DXT.VALUE LIKE 'I28.9'
              OR DXT.VALUE LIKE 'T80.0XXA' OR DXT.VALUE LIKE 'T82.817A' OR DXT.VALUE LIKE 'T82.818A'
              OR DXT.VALUE LIKE '415.1%' OR DXT.VALUE LIKE '416.%' OR DXT.VALUE LIKE '417.9'
             THEN 1 ELSE 0 END) AS ELIX_PULMCIRC,

    MAX(CASE WHEN DXT.VALUE LIKE 'N18.3%' OR DXT.VALUE LIKE 'N18.4%' OR DXT.VALUE LIKE 'N18.5%'
              OR DXT.VALUE LIKE 'N18.6%' OR DXT.VALUE LIKE 'N18.9%' OR DXT.VALUE = 'N19'
              OR DXT.VALUE LIKE 'Z49.%' OR DXT.VALUE LIKE 'Z91.15' OR DXT.VALUE LIKE 'Z94.0'
              OR DXT.VALUE LIKE 'Z99.2' OR DXT.VALUE LIKE '585.3%' OR DXT.VALUE LIKE '585.4%'
              OR DXT.VALUE LIKE '585.5%' OR DXT.VALUE LIKE '585.6%' OR DXT.VALUE LIKE '585.9%'
              OR DXT.VALUE LIKE '586' OR DXT.VALUE LIKE 'V42.0' OR DXT.VALUE LIKE 'V45.1'
              OR DXT.VALUE LIKE 'V56%'
             THEN 1 ELSE 0 END) AS ELIX_RENLFAIL,

    MAX(CASE WHEN DXT.VALUE LIKE 'C00.%' OR DXT.VALUE LIKE 'C01%' OR DXT.VALUE LIKE 'C02.%'
              OR DXT.VALUE LIKE 'C03.%' OR DXT.VALUE LIKE 'C04.%' OR DXT.VALUE LIKE 'C05.%'
              OR DXT.VALUE LIKE 'C06.%' OR DXT.VALUE LIKE 'C07' OR DXT.VALUE LIKE 'C08.%'
              OR DXT.VALUE LIKE 'C09.%' OR DXT.VALUE LIKE 'C10.%' OR DXT.VALUE LIKE 'C11.%'
              OR DXT.VALUE LIKE 'C12' OR DXT.VALUE LIKE 'C13.%' OR DXT.VALUE LIKE 'C14.%'
              OR DXT.VALUE LIKE 'C15.%' OR DXT.VALUE LIKE 'C16.%' OR DXT.VALUE LIKE 'C17.%'
              OR DXT.VALUE LIKE 'C18.%' OR DXT.VALUE LIKE 'C19' OR DXT.VALUE LIKE 'C20'
              OR DXT.VALUE LIKE 'C21.%' OR DXT.VALUE LIKE 'C22.%' OR DXT.VALUE LIKE 'C23'
              OR DXT.VALUE LIKE 'C24.%' OR DXT.VALUE LIKE 'C25.%' OR DXT.VALUE LIKE 'C26.%'
              OR DXT.VALUE LIKE 'C30.%' OR DXT.VALUE LIKE 'C31.%' OR DXT.VALUE LIKE 'C32.%'
              OR DXT.VALUE LIKE 'C33' OR DXT.VALUE LIKE 'C34.%' OR DXT.VALUE LIKE 'C37'
              OR DXT.VALUE LIKE 'C38.%' OR DXT.VALUE LIKE 'C39.%' OR DXT.VALUE LIKE 'C40.%'
              OR DXT.VALUE LIKE 'C41.%' OR DXT.VALUE LIKE 'C43.%' OR DXT.VALUE LIKE 'C45.%'
              OR DXT.VALUE LIKE 'C47.%' OR DXT.VALUE LIKE 'C48.%' OR DXT.VALUE LIKE 'C49.%'
              OR DXT.VALUE LIKE 'C4A.%' OR DXT.VALUE LIKE 'C50.%' OR DXT.VALUE LIKE 'C51.%'
              OR DXT.VALUE LIKE 'C52' OR DXT.VALUE LIKE 'C53.%' OR DXT.VALUE LIKE 'C54.%'
              OR DXT.VALUE LIKE 'C55' OR DXT.VALUE LIKE 'C56.%' OR DXT.VALUE LIKE 'C57.%'
              OR DXT.VALUE LIKE 'C58' OR DXT.VALUE LIKE 'C60.%' OR DXT.VALUE LIKE 'C61'
              OR DXT.VALUE LIKE 'C62.%' OR DXT.VALUE LIKE 'C63.%' OR DXT.VALUE LIKE 'C64.%'
              OR DXT.VALUE LIKE 'C65.%' OR DXT.VALUE LIKE 'C66.%' OR DXT.VALUE LIKE 'C67.%'
              OR DXT.VALUE LIKE 'C68.%' OR DXT.VALUE LIKE 'C69.%' OR DXT.VALUE LIKE 'C70.%'
              OR DXT.VALUE LIKE 'C71.%' OR DXT.VALUE LIKE 'C72.%' OR DXT.VALUE LIKE 'C73'
              OR DXT.VALUE LIKE 'C74.%' OR DXT.VALUE LIKE 'C75.%' OR DXT.VALUE LIKE 'C76.%'
              OR DXT.VALUE LIKE 'C7A.%' OR DXT.VALUE LIKE 'C7B.%' OR DXT.VALUE LIKE 'D03.%'
              OR DXT.VALUE LIKE 'D03.0' OR DXT.VALUE LIKE 'D03.10' OR DXT.VALUE LIKE 'D03.11'
              OR DXT.VALUE LIKE 'D03.12' OR DXT.VALUE LIKE 'D03.20' OR DXT.VALUE LIKE 'D03.21'
              OR DXT.VALUE LIKE 'D03.22' OR DXT.VALUE LIKE 'D03.30' OR DXT.VALUE LIKE 'D03.39'
              OR DXT.VALUE LIKE 'D03.4' OR DXT.VALUE LIKE 'D03.51' OR DXT.VALUE LIKE 'D03.52'
              OR DXT.VALUE LIKE 'D03.59' OR DXT.VALUE LIKE 'D03.60' OR DXT.VALUE LIKE 'D03.61'
              OR DXT.VALUE LIKE 'D03.62' OR DXT.VALUE LIKE 'D03.70' OR DXT.VALUE LIKE 'D03.71'
              OR DXT.VALUE LIKE 'D03.72' OR DXT.VALUE LIKE 'D03.8' OR DXT.VALUE LIKE 'D03.9'
             THEN 1 ELSE 0 END) AS ELIX_TUMOR,

    MAX(CASE WHEN DXT.VALUE LIKE 'K25.%' OR DXT.VALUE LIKE 'K26.%' OR DXT.VALUE LIKE 'K27.%'
              OR DXT.VALUE LIKE 'K28.%' OR DXT.VALUE LIKE '531.%' OR DXT.VALUE LIKE '532.%'
              OR DXT.VALUE LIKE '533.%' OR DXT.VALUE LIKE '534.%'
             THEN 1 ELSE 0 END) AS ELIX_ULCER,

    MAX(CASE WHEN DXT.VALUE LIKE 'A52.03' OR DXT.VALUE LIKE 'I05.%' OR DXT.VALUE LIKE 'I06.%'
              OR DXT.VALUE LIKE 'I07.%' OR DXT.VALUE LIKE 'I08.%' OR DXT.VALUE LIKE 'I09.1'
              OR DXT.VALUE LIKE 'I09.89' OR DXT.VALUE LIKE 'I34.%' OR DXT.VALUE LIKE 'I35.%'
              OR DXT.VALUE LIKE 'I36.%' OR DXT.VALUE LIKE 'I37.%' OR DXT.VALUE IN ('I38','I39')
              OR DXT.VALUE LIKE 'Q23.%' OR DXT.VALUE LIKE 'Z95.2' OR DXT.VALUE LIKE 'Z95.3'
              OR DXT.VALUE LIKE 'Z95.4'
             THEN 1 ELSE 0 END) AS ELIX_VALVE,

    MAX(CASE WHEN DXT.VALUE LIKE 'E40%' OR DXT.VALUE LIKE 'E41%' OR DXT.VALUE LIKE 'E42%'
              OR DXT.VALUE LIKE 'E43%' OR DXT.VALUE LIKE 'E44.%' OR DXT.VALUE LIKE 'E45'
              OR DXT.VALUE LIKE 'E46' OR DXT.VALUE LIKE 'E64.0' OR DXT.VALUE LIKE 'R63.4'
              OR DXT.VALUE LIKE 'R63.6'
             THEN 1 ELSE 0 END) AS ELIX_WGHTLOSS

FROM CTE_SURGERY_BASE S
LEFT JOIN CABOODLE.DIAGNOSISEVENTFACT DEF
    ON S.PDK = DEF.PATIENTDURABLEKEY
   AND DEF.COUNT = 1
   AND DEF.TYPE IN ('Encounter Diagnosis', 'Encounter Diagnosis from External Source')
LEFT JOIN CABOODLE.DIAGNOSISTERMINOLOGYDIM DXT
    ON DEF.DIAGNOSISKEY = DXT.DIAGNOSISKEY
   AND DXT.TYPE = 'ICD-10-CM'
GROUP BY S.SURGICALCASEKEY, S.PDK


),


CTE_IMPLANT_SUPPLY AS (
    SELECT
        SSU.SURGICALCASEKEY,
        LISTAGG(DISTINCT SSD.NAME, ' || ')
            WITHIN GROUP (ORDER BY SSD.NAME) AS IMPLANT_SUPPLY_NAME
    FROM CABOODLE.SURGICALSUPPLYUSEFACT SSU
    INNER JOIN CABOODLE.SURGICALSUPPLYDIM SSD
        ON SSU.SURGICALSUPPLYKEY = SSD.SURGICALSUPPLYKEY
    WHERE SSU.COUNT = 1
      AND SSD.ISCURRENT = 1
      AND SSD.TYPE ILIKE '%implant%'
    GROUP BY SSU.SURGICALCASEKEY
),




CTE_PREIMAGING AS (
    SELECT
        x.SURGICALCASEKEY,
        x.PDK,
        MAX(CASE WHEN x.modality_group = 'MRI'  AND x.rn = 1 THEN CAST(x.ExamStartInstant AS DATE) END) AS PREOP_MRI_DATE,
        MAX(CASE WHEN x.modality_group = 'XRAY' AND x.rn = 1 THEN CAST(x.ExamStartInstant AS DATE) END) AS PREOP_XRAY_DATE,
        MAX(CASE WHEN x.modality_group = 'CT'   AND x.rn = 1 THEN CAST(x.ExamStartInstant AS DATE) END) AS PREOP_CT_DATE,
        MAX(CASE WHEN x.modality_group = 'DEXA' AND x.rn = 1 THEN CAST(x.ExamStartInstant AS DATE) END) AS PREOP_DEXA_DATE,
        MAX(CASE WHEN x.modality_group = 'ULTRASOUND' AND x.rn = 1 THEN CAST(x.ExamStartInstant AS DATE) END) AS PREOP_ULTRASOUND_DATE
    FROM (
        SELECT
            S.SURGICALCASEKEY,
            S.PDK,
            img.ExamStartInstant,
            CASE
                WHEN (proceduredim.Name) iLIKE 'mr%' THEN 'MRI'
                WHEN (proceduredim.Name) iLIKE 'xr%' OR LOWER(proceduredim.Name) LIKE 'xray%' THEN 'XRAY'
                WHEN (proceduredim.Name) ILIKE 'ct%' THEN 'CT'
                WHEN (proceduredim.Name) ILIKE 'dxa%' THEN 'DEXA'
                WHEN (proceduredim.Name) ILIKE 'us%' THEN 'ULTRASOUND'
                ELSE NULL
            END AS modality_group,
            ROW_NUMBER() OVER (
                PARTITION BY S.SURGICALCASEKEY,
                             CASE
                                 WHEN (proceduredim.Name) ILIKE 'mr%' THEN 'MRI'
                                 WHEN (proceduredim.Name) ILIKE 'xr%' OR LOWER(proceduredim.Name) LIKE 'xray%' THEN 'XRAY'
                                 WHEN (proceduredim.Name) ILIKE 'ct%' THEN 'CT'
                                 WHEN (proceduredim.Name) ILIKE 'dxa%' THEN 'DEXA'
                                 WHEN (proceduredim.Name) ILIKE 'us%' THEN 'ULTRASOUND'
                                 ELSE NULL
                             END
                ORDER BY img.ExamStartInstant DESC
            ) AS rn
        FROM CTE_SURGERY_BASE S
        JOIN CABOODLE.IMAGINGFACT img
            ON S.PDK = img.PATIENTDURABLEKEY
        JOIN CABOODLE.PROCEDUREDIM proceduredim
            ON img.FIRSTPROCEDUREDURABLEKEY = proceduredim.DurableKey
        WHERE img.ExamStartInstant < CAST(S.SURGERY_DATE AS TIMESTAMP_NTZ)
          AND (
                (proceduredim.Name) ILIKE 'mr%'
             OR (proceduredim.Name) ILIKE 'xr%'
             OR (proceduredim.Name) ILIKE 'xray%'
             OR (proceduredim.Name) ILIKE 'ct%'
             OR (proceduredim.Name) ILIKE 'dxa%'
             OR (proceduredim.Name) ILIKE 'us%'
          )
    ) x
    WHERE x.modality_group IS NOT NULL
    GROUP BY
        x.SURGICALCASEKEY,
        x.PDK
),

CTE_POSTOP_MEDS AS (
    SELECT
        x.SURGICALCASEKEY,
        LISTAGG(DISTINCT CASE WHEN x.MED_CLASS = 'STEROID' THEN x.MED_NAME END, ' || ')
            WITHIN GROUP (ORDER BY CASE WHEN x.MED_CLASS = 'STEROID' THEN x.MED_NAME END) AS STEROID_USE,
        LISTAGG(DISTINCT CASE WHEN x.MED_CLASS = 'NSAID' THEN x.MED_NAME END, ' || ')
            WITHIN GROUP (ORDER BY CASE WHEN x.MED_CLASS = 'NSAID' THEN x.MED_NAME END) AS NSAID_USE
    FROM (
        SELECT DISTINCT
            S.SURGICALCASEKEY,
            COALESCE(MD.NAME, MD.GENERICNAME) AS MED_NAME,
            CASE
                WHEN UPPER(COALESCE(MD.NAME, '')) LIKE '%PREDNISONE%'
                  OR UPPER(COALESCE(MD.NAME, '')) LIKE '%METHYLPREDNISOLONE%'
                  OR UPPER(COALESCE(MD.NAME, '')) LIKE '%DEXAMETHASONE%'
                  OR UPPER(COALESCE(MD.NAME, '')) LIKE '%HYDROCORTISONE%'
                  OR UPPER(COALESCE(MD.NAME, '')) LIKE '%PREDNISOLONE%'
                  OR UPPER(COALESCE(MD.NAME, '')) LIKE '%TRIAMCINOLONE%'
                  OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%PREDNISONE%'
                  OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%METHYLPREDNISOLONE%'
                  OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%DEXAMETHASONE%'
                  OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%HYDROCORTISONE%'
                  OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%PREDNISOLONE%'
                  OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%TRIAMCINOLONE%'
                THEN 'STEROID'
                WHEN UPPER(COALESCE(MD.NAME, '')) LIKE '%IBUPROFEN%'
                  OR UPPER(COALESCE(MD.NAME, '')) LIKE '%NAPROXEN%'
                  OR UPPER(COALESCE(MD.NAME, '')) LIKE '%KETOROLAC%'
                  OR UPPER(COALESCE(MD.NAME, '')) LIKE '%MELOXICAM%'
                  OR UPPER(COALESCE(MD.NAME, '')) LIKE '%CELECOXIB%'
                  OR UPPER(COALESCE(MD.NAME, '')) LIKE '%DICLOFENAC%'
                  OR UPPER(COALESCE(MD.NAME, '')) LIKE '%INDOMETHACIN%'
                  OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%IBUPROFEN%'
                  OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%NAPROXEN%'
                  OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%KETOROLAC%'
                  OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%MELOXICAM%'
                  OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%CELECOXIB%'
                  OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%DICLOFENAC%'
                  OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%INDOMETHACIN%'
                THEN 'NSAID'
            END AS MED_CLASS
        FROM CTE_SURGERY_BASE S
        JOIN CABOODLE.MEDICATIONEVENTFACT ME
            ON S.PDK = ME.PATIENTDURABLEKEY
        JOIN CABOODLE.MEDICATIONDIM MD
            ON ME.MEDICATIONKEY = MD.MEDICATIONKEY
        JOIN CABOODLE.DATEDIM MED_DT
            ON ME.STARTDATEKEY = MED_DT.DATEKEY
        WHERE MED_DT.DATEVALUE >= S.SURGERY_DATE
          AND MED_DT.DATEVALUE < DATEADD(DAY, 11, S.SURGERY_DATE)
          AND (
                UPPER(COALESCE(MD.NAME, '')) LIKE '%PREDNISONE%'
             OR UPPER(COALESCE(MD.NAME, '')) LIKE '%METHYLPREDNISOLONE%'
             OR UPPER(COALESCE(MD.NAME, '')) LIKE '%DEXAMETHASONE%'
             OR UPPER(COALESCE(MD.NAME, '')) LIKE '%HYDROCORTISONE%'
             OR UPPER(COALESCE(MD.NAME, '')) LIKE '%PREDNISOLONE%'
             OR UPPER(COALESCE(MD.NAME, '')) LIKE '%TRIAMCINOLONE%'
             OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%PREDNISONE%'
             OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%METHYLPREDNISOLONE%'
             OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%DEXAMETHASONE%'
             OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%HYDROCORTISONE%'
             OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%PREDNISOLONE%'
             OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%TRIAMCINOLONE%'
             OR UPPER(COALESCE(MD.NAME, '')) LIKE '%IBUPROFEN%'
             OR UPPER(COALESCE(MD.NAME, '')) LIKE '%NAPROXEN%'
             OR UPPER(COALESCE(MD.NAME, '')) LIKE '%KETOROLAC%'
             OR UPPER(COALESCE(MD.NAME, '')) LIKE '%MELOXICAM%'
             OR UPPER(COALESCE(MD.NAME, '')) LIKE '%CELECOXIB%'
             OR UPPER(COALESCE(MD.NAME, '')) LIKE '%DICLOFENAC%'
             OR UPPER(COALESCE(MD.NAME, '')) LIKE '%INDOMETHACIN%'
             OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%IBUPROFEN%'
             OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%NAPROXEN%'
             OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%KETOROLAC%'
             OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%MELOXICAM%'
             OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%CELECOXIB%'
             OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%DICLOFENAC%'
             OR UPPER(COALESCE(MD.GENERICNAME, '')) LIKE '%INDOMETHACIN%'
          )
    ) x
    WHERE x.MED_CLASS IS NOT NULL
    GROUP BY x.SURGICALCASEKEY
),

HspReadmitDates_30 AS (
    SELECT
        SurgicalCaseKey,
        LISTAGG(TO_VARCHAR(admt_dt), ', ')
            WITHIN GROUP (ORDER BY admt_dt ASC) AS ReadmissionDate_30D,
        LISTAGG(dxname, ', ')
            WITHIN GROUP (ORDER BY admt_dt ASC) AS ReadmissionReason_30D
    FROM (
        SELECT DISTINCT
            idx.SURGICALCASEKEY AS SurgicalCaseKey,
            hdd.DATEVALUE AS admt_dt,
            COALESCE(dx.NAME, 'Not documented') AS dxname,
            ROW_NUMBER() OVER (
                PARTITION BY idx.SURGICALCASEKEY, hsp.ADMISSIONDATEKEY
                ORDER BY hsp.ADMISSIONDATEKEY ASC
            ) AS rn
        FROM CTE_INDEX_STAY idx
        JOIN CABOODLE.HOSPITALADMISSIONFACT hsp
            ON hsp.PATIENTDURABLEKEY = idx.PDK
           AND hsp.ADMISSIONDATEKEY > idx.DISCHARGEDATEKEY
        JOIN CABOODLE.DATEDIM hdd
            ON hsp.ADMISSIONDATEKEY = hdd.DATEKEY
        JOIN CABOODLE.ENCOUNTERFACT enc
            ON hsp.ENCOUNTERKEY = enc.ENCOUNTERKEY
        LEFT JOIN STAGE.RDSC.RDSC_readmission_op_35_all_table readmit
            ON enc.ENCOUNTEREPICCSN = readmit.REVISIT_ENCNTR_ID
        LEFT JOIN CABOODLE.DIAGNOSISTERMINOLOGYDIM t
            ON hsp.PRINCIPALPROBLEMKEY = t.DIAGNOSISKEY
        LEFT JOIN CABOODLE.DIAGNOSISDIM dx
            ON hsp.PRINCIPALPROBLEMKEY = dx.DIAGNOSISKEY
        WHERE t.TYPE = 'ICD-10-CM'
          AND hsp.PRINCIPALPROBLEMKEY IS NOT NULL
          AND hsp.ADMISSIONDATEKEY IS NOT NULL
          AND DATEDIFF(DAY, idx.DISCHARGE_DATE, hdd.DATEVALUE) BETWEEN 1 AND 30
        QUALIFY rn = 1
    ) s
    GROUP BY SurgicalCaseKey
),

HspReadmitDates_90 AS (
    SELECT
        SurgicalCaseKey,
        LISTAGG(TO_VARCHAR(admt_dt), ', ')
            WITHIN GROUP (ORDER BY admt_dt ASC) AS ReadmissionDate_90D,
        LISTAGG(dxname, ', ')
            WITHIN GROUP (ORDER BY admt_dt ASC) AS ReadmissionReason_90D
    FROM (
        SELECT DISTINCT
            idx.SURGICALCASEKEY AS SurgicalCaseKey,
            hdd.DATEVALUE AS admt_dt,
            COALESCE(dx.NAME, 'Not documented') AS dxname,
            ROW_NUMBER() OVER (
                PARTITION BY idx.SURGICALCASEKEY, hsp.ADMISSIONDATEKEY
                ORDER BY hsp.ADMISSIONDATEKEY ASC
            ) AS rn
        FROM CTE_INDEX_STAY idx
        JOIN CABOODLE.HOSPITALADMISSIONFACT hsp
            ON hsp.PATIENTDURABLEKEY = idx.PDK
           AND hsp.ADMISSIONDATEKEY > idx.DISCHARGEDATEKEY
        JOIN CABOODLE.DATEDIM hdd
            ON hsp.ADMISSIONDATEKEY = hdd.DATEKEY
        JOIN CABOODLE.ENCOUNTERFACT enc
            ON hsp.ENCOUNTERKEY = enc.ENCOUNTERKEY
        LEFT JOIN STAGE.RDSC.RDSC_readmission_op_35_all_table readmit
            ON enc.ENCOUNTEREPICCSN = readmit.REVISIT_ENCNTR_ID
        LEFT JOIN CABOODLE.DIAGNOSISTERMINOLOGYDIM t
            ON hsp.PRINCIPALPROBLEMKEY = t.DIAGNOSISKEY
        LEFT JOIN CABOODLE.DIAGNOSISDIM dx
            ON hsp.PRINCIPALPROBLEMKEY = dx.DIAGNOSISKEY
        WHERE t.TYPE = 'ICD-10-CM'
          AND hsp.PRINCIPALPROBLEMKEY IS NOT NULL
          AND hsp.ADMISSIONDATEKEY IS NOT NULL
          AND DATEDIFF(DAY, idx.DISCHARGE_DATE, hdd.DATEVALUE) BETWEEN 31 AND 90
        QUALIFY rn = 1
    ) s
    GROUP BY SurgicalCaseKey
),

CTE_ED_VISIT_30 AS (
    SELECT
        SurgicalCaseKey,
        MAX(CASE WHEN rn = 1 THEN ed_dt END) AS ED_VISIT_DATE_30D,
        MAX(CASE WHEN rn = 1 THEN ed_reason END) AS ED_VISIT_REASON_30D
    FROM (
        SELECT
            S.SURGICALCASEKEY AS SurgicalCaseKey,
            edd.DATEVALUE AS ed_dt,
            COALESCE(ccd.NAME, 'Not documented') AS ed_reason,
            ROW_NUMBER() OVER (
                PARTITION BY S.SURGICALCASEKEY
                ORDER BY edd.DATEVALUE ASC, ev.ARRIVALDATEKEY ASC
            ) AS rn
        FROM CTE_SURGERY_BASE S
        JOIN CABOODLE.EDVISITFACT ev
            ON ev.PATIENTDURABLEKEY = S.PDK
        JOIN CABOODLE.DATEDIM edd
            ON ev.ARRIVALDATEKEY = edd.DATEKEY
        LEFT JOIN CABOODLE.CHIEFCOMPLAINTDIM ccd
            ON ev.PRIMARYCHIEFCOMPLAINTKEY = ccd.CHIEFCOMPLAINTKEY
        WHERE DATEDIFF(DAY, S.SURGERY_DATE, edd.DATEVALUE) BETWEEN 0 AND 30
    ) x
    GROUP BY SurgicalCaseKey
)

SELECT
    S.SURGICALCASEKEY,
    S.SURGICALCASEEPICID,
     S.DEPARTMENTNAME,
    PAT.PRIMARYMRN,
    PAT.NAME AS PATIENT_NAME,
    PAT.BIRTHDATE,
    DATEDIFF(YEAR, PAT.BIRTHDATE, S.SURGERY_DATE)
      - CASE
            WHEN DATEADD(YEAR, DATEDIFF(YEAR, PAT.BIRTHDATE, S.SURGERY_DATE), PAT.BIRTHDATE) > S.SURGERY_DATE
            THEN 1 ELSE 0
        END AS AGE_AT_SURGERY,
          CASE
    WHEN (
        DATEDIFF(YEAR, PAT.BIRTHDATE, S.SURGERY_DATE)
        - CASE
              WHEN DATEADD(
                       YEAR,
                       DATEDIFF(YEAR, PAT.BIRTHDATE, S.SURGERY_DATE),
                       PAT.BIRTHDATE
                   ) > S.SURGERY_DATE
              THEN 1
              ELSE 0
          END
    ) >= 65
    THEN 'Yes'
    ELSE 'No'
END AS AGE_OVER_65_FLAG,
    PAT.SEX,
    PAT.FIRSTRACE,
    PAT.ETHNICITY,
    PAT.HIGHESTLEVELOFEDUCATION,
    PAT.POSTALCODE,
    PAT.MARITALSTATUS,
    PAT.ADDRESS,
  

    S.SURGERYDATEKEY,
    S.SURGERY_DATE,
    S.SURGEON_NAME,
    CP.PROCEDURE_NAME,
    CP.PRIMARYCPT,
    CP.CPTCODE,
    
    --S.PRIMARYPROCEDUREAPPROACH,
    S.PRIMARYANESTHESIATYPE,
    --S.PROCEDURENOTPERFORMED,
    S.ANESTHESIASTARTDATEKEY,
    S.ANESTHESIASTARTTIMEOFDAYKEY,
    S.ANESTHESIASTOPTIMEOFDAYKEY,
    S.PROCEDURESTARTTIMEOFDAYKEY,
    S.PROCEDURECOMPLETETIMEOFDAYKEY,
    S.HADSURGICALSITEINFECTION,
    S.SURGICALSITEINFECTIONRISKSCORE,
    S.WASPERIPHERALNERVEBLOCKPERFORMED,
    S.HADOTHERCOMPLICATION,
    S.RETURNTOSURGERYINDAYS,
      IMP.IMPLANT_SUPPLY_NAME,
    S.TOTALCOST,
    S.HOSPITALSURGICALCOST,
    S.IMPLANTABLESUPPLYUSEDCOST,
    C.OSA_FLAG,
C.CAD_MI_FLAG,
C.ARRHYTHMIA_FLAG,
C.ANXIETY_FLAG,
C.DEMENTIA_FLAG,
C.FUNCTIONAL_DISABILITY_FLAG,

EM.ELIX_CHF,
EM.ELIX_AIDS,
EM.ELIX_ALCOHOL,
EM.ELIX_ANEMDEF,
EM.ELIX_ARTH,
EM.ELIX_BLDLOSS,
EM.ELIX_CHRNLUNG,
EM.ELIX_COAG,
EM.ELIX_DEPRESS,
EM.ELIX_DM,
EM.ELIX_DMCX,
EM.ELIX_DRUG,
EM.ELIX_HHRWCHF,
EM.ELIX_HHRWHRF,
EM.ELIX_HHRWOHRF,
EM.ELIX_HHRWRF,
EM.ELIX_HRENWORF,
EM.ELIX_HRENWRF,
EM.ELIX_HTN,
EM.ELIX_HTNCX,
EM.ELIX_HTNPREG,
EM.ELIX_HTNWCHF,
EM.ELIX_HTNWOCHF,
EM.ELIX_HYPOTHY,
EM.ELIX_LIVER,
EM.ELIX_LYMPH,
EM.ELIX_LYTES,
EM.ELIX_METS,
EM.ELIX_NEURO,
EM.ELIX_OBESE,
EM.ELIX_OHTNPREG,
EM.ELIX_PARA,
EM.ELIX_PERIVASC,
EM.ELIX_PSYCH,
EM.ELIX_PULMCIRC,
EM.ELIX_RENLFAIL,
EM.ELIX_TUMOR,
EM.ELIX_ULCER,
EM.ELIX_VALVE,
EM.ELIX_WGHTLOSS,


    BA.FINANCIALCLASS,
    BA.ADMISSIONDATEKEY,
    BA.ADMISSIONTIMEOFDAYKEY,
    BA.DISCHARGEDATEKEY,
    BA.DISCHARGETIMEOFDAYKEY,
    BA.INPATIENTBILLINGLENGTHOFSTAYINDAYS,

    D.DIAGNOSIS,

    C.ASARATING_X,
    CASE
WHEN UPPER(TRIM(S.ASARATING_X)) IN ('HEALTHY') THEN 1
WHEN UPPER(TRIM(S.ASARATING_X)) IN ('MILD SYSTEMIC DISEASE') THEN 2
WHEN UPPER(TRIM(S.ASARATING_X)) IN ('SEVERE SYSTEMIC DISEASE') THEN 3
WHEN UPPER(TRIM(S.ASARATING_X)) IN (
'INCAPACITATING DISEASE',
'SEVERE SYSTEMIC DISEASE THAT IS A CONSTANT THREAT TO LIFE'
) THEN 4
WHEN UPPER(TRIM(S.ASARATING_X)) IN ('MORBUND') THEN 5
WHEN UPPER(TRIM(S.ASARATING_X)) IN ('BRAIN DEAD') THEN 6
WHEN UPPER(TRIM(S.ASARATING_X)) IN (
'*UNSPECIFIED', 'UNSPECIFIED',
'*NOT APPLICABLE', 'NOT APPLICABLE',
'*UNKNOWN', 'UNKNOWN',
'*DELETED', 'DELETED'
) THEN NULL
ELSE NULL
END AS ASA_SCORE,

    C.CHARLSON_COMORBIDITY_INDEX,
    C.SMOKING_STATUS,
    C.BODYMASSINDEX,
    CASE
    WHEN C.BODYMASSINDEX IS NULL THEN 'Unknown'
    WHEN C.BODYMASSINDEX >= 30 THEN 'Yes'
    ELSE 'No'
END AS BMI_OVER_30_FLAG,
    C.HEIGHT,
    C.WEIGHT,
    C.FUNCTIONALSTATUS,
    C.LIVINGSITUATION,
    C.MENTALHEALTHSTATUS,
    C.RECENT_HOSPITALIZATION_90D_FLAG,
   

    SD.SOCIALDETERMINANTDOMAIN,
    SD.LEVELOFCONCERN,
    SD.ENTRYINTERPRETATION,

    PM.STEROID_USE,
    PM.NSAID_USE,
      PI.PREOP_MRI_DATE,
    PI.PREOP_XRAY_DATE,
    PI.PREOP_CT_DATE,
    PI.PREOP_DEXA_DATE,
    PI.PREOP_ULTRASOUND_DATE,

    R30.ReadmissionDate_30D,
    R30.ReadmissionReason_30D,
    R90.ReadmissionDate_90D,
    R90.ReadmissionReason_90D,

    ED.ED_VISIT_DATE_30D,
    ED.ED_VISIT_REASON_30D

FROM CTE_SURGERY_BASE S
INNER JOIN CABOODLE.PATIENTDIM PAT
    ON S.PDK = PAT.DURABLEKEY
   AND PAT.ISCURRENT = 1
   AND PAT.ISVALID = 1
LEFT JOIN CTE_CASE_PROCEDURE CP
    ON S.SURGICALCASEKEY = CP.SURGICALCASEKEY
LEFT JOIN CTE_BILLING_ACCOUNT BA
    ON S.SURGICALCASEKEY = BA.SURGICALCASEKEY
LEFT JOIN CTE_DIAGNOSIS D
    ON S.SURGICALCASEKEY = D.SURGICALCASEKEY
LEFT JOIN CTE_COMORBIDITIES C
    ON S.SURGICALCASEKEY = C.SURGICALCASEKEY
LEFT JOIN CTE_ELIX_MISSING EM
    ON S.SURGICALCASEKEY = EM.SURGICALCASEKEY
LEFT JOIN CTE_SOCIAL_DETERMINANTS SD
    ON S.SURGICALCASEKEY = SD.SURGICALCASEKEY
LEFT JOIN CTE_POSTOP_MEDS PM
    ON S.SURGICALCASEKEY = PM.SURGICALCASEKEY
LEFT JOIN CTE_IMPLANT_SUPPLY IMP
    ON S.SURGICALCASEKEY = IMP.SURGICALCASEKEY
LEFT JOIN CTE_PREIMAGING PI
    ON S.SURGICALCASEKEY = PI.SURGICALCASEKEY
LEFT JOIN HspReadmitDates_30 R30
    ON S.SURGICALCASEKEY = R30.SurgicalCaseKey
LEFT JOIN HspReadmitDates_90 R90
    ON S.SURGICALCASEKEY = R90.SurgicalCaseKey
LEFT JOIN CTE_ED_VISIT_30 ED
    ON S.SURGICALCASEKEY = ED.SurgicalCaseKey
ORDER BY S.SURGICALCASEKEY DESC, PAT.PRIMARYMRN;